/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cz_muni_fi_kurcik_kgs_util_Majka */

#ifndef _Included_cz_muni_fi_kurcik_kgs_util_Majka
#define _Included_cz_muni_fi_kurcik_kgs_util_Majka
#ifdef __cplusplus
extern "C" {
#endif
#undef cz_muni_fi_kurcik_kgs_util_Majka_ADD_DIACRITICS
#define cz_muni_fi_kurcik_kgs_util_Majka_ADD_DIACRITICS 1L
#undef cz_muni_fi_kurcik_kgs_util_Majka_IGNORE_CASE
#define cz_muni_fi_kurcik_kgs_util_Majka_IGNORE_CASE 2L
#undef cz_muni_fi_kurcik_kgs_util_Majka_DISALLOW_LOWERCASE
#define cz_muni_fi_kurcik_kgs_util_Majka_DISALLOW_LOWERCASE 4L
/*
 * Class:     cz_muni_fi_kurcik_kgs_util_Majka
 * Method:    find
 * Signature: (Ljava/lang/String;Ljava/lang/String;I)[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_cz_muni_fi_kurcik_kgs_util_Majka_find
  (JNIEnv *, jobject, jstring, jstring, jint);

/*
 * Class:     cz_muni_fi_kurcik_kgs_util_Majka
 * Method:    findAll
 * Signature: (Ljava/lang/String;[Ljava/lang/String;II)[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_cz_muni_fi_kurcik_kgs_util_Majka_findAll
  (JNIEnv *, jobject, jstring, jobjectArray, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
